### ISSUE TITLE
The project  already available?

### ISSUE THREAD

**Issue by d18zj** [WenningQiu/SourceLink.Subversion#1]
This is my .csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <!-- Optional: Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->

    <RepositoryType>svn</RepositoryType>
    <RepositoryUrl>https://doerkfsrv:8443/svn/R9/utiltest/Util</RepositoryUrl>
    <!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
    <EmbedAllSources>true</EmbedAllSources>
    <!--<EmbedUntrackedSources>true</EmbedUntrackedSources>-->
    <!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <Version>1.0.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SourceLink.VisualSVN" Version="1.0.1" PrivateAssets="all" />
  </ItemGroup>
 
</Project>
```

**Comment by d18zj** [comment]
This is my .CSPROj file:
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    

    <RepositoryType>svn</RepositoryType>
    <RepositoryUrl>https://doerkfsrv:8443/svn/R9/utiltest/Util</RepositoryUrl>
    
    <EmbedAllSources>true</EmbedAllSources>
    
    
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <Version>1.0.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SourceLink.VisualSVN" Version="1.0.1" PrivateAssets="all" />
  </ItemGroup>
 
</Project>`

**Comment by WenningQiu** [comment]
@d18zj Yes that's all you need. If you had installed the sourcelink tool (https://www.nuget.org/packages/SourceLink/), you should be able to verify that the SourceLink URL is embedded in your assembly's PDB file.
